# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["<dmilitaru@fastly.com>"]
description = "Machine learning inference at the edge and Object Store"
language = "rust"
manifest_version = 2
name = "edgeml-objstore"
service_id = "oofCZrn4JHkjdtm9lySZK1"

# [local_server]
#   object_store.models = []